### ISSUE TITLE
POST: Por que estou deixando o Google?

### ISSUE THREAD

**Issue by diessica** [danielfilho/blog.dnl.dev#23]
Admiro a tua iniciativa, principalmente porque também acredito que devemos prezar, acima de tudo, pela nossa privacidade, mesmo quando se acredita falaciosamente que _nada temos a esconder/temer_.

Vejo, no entanto, que a frase

> Quando você não paga por um produto (comercial), você é o produto.

é o alicerce da tua motivação para deixar de lado alguns serviços fornecidos pela Google.

Referente a essa citação, gostaria muito de compartilhar contigo um artigo: [I’m Not The Product, But I Play One On The Internet](http://powazek.com/posts/3229) - este, principalmente, pois contra-argumenta a citação e pode, inclusive, mudar sua opinião sobre o assunto (não sobre a questão da privacidade, não sobre a Google, mas especificamente sobre a declaração).

De importância menor, há também o artigo [You Are Not the Product: The Coming Revolution in Social Networks](http://www.the-vital-edge.com/not-the-product/), que sugere visões alternativas e "soluções" para a situação problematizada na citação.

**Comment by danielfilho** [comment]
são dois textos bem extensos que, com certeza, vou ler em breve.

valeu por compartilhar, @diessica :grimacing:
